server {
    listen 80;
    root /usr/share/nginx/html;

    # frontend files
    location / {
        index index.html;
        try_files $uri /index.html;
    }

    # API proxy
    location /api/ {
        proxy_pass http://backend:8000/api/;
    }

    # gzip (performance)
    gzip on;
    gzip_types text/plain application/json application/javascript text/css;

    # caching
    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
        expires 1d;
        add_header Cache-Control "public";
    }
}