version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - notes-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - notes-net
    
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - notes-net

volumes:
  mysql-data:
networks:
  notes-net: