# Generated by Django 4.2.30 on 2026-06-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user_clerk_id',
            field=models.CharField(db_index=True, default='temp_user', max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user_clerk_id', '-created_at'], name='notes_note_user_cl_dbd165_idx'),
        ),
    ]
